
protocol 'jdbc:derby:';
connect 'discussion;create=true';

create table ATTACHMENT (
ATTACHMENT_ID INTEGER NOT NULL UNIQUE,
CONTENT VARCHAR(1024),
FILENAME VARCHAR(255),
MESSAGE_ID INTEGER NOT NULL
);

create table BOARD (
ALLOWS_POSTING INTEGER,
BOARD_ID INTEGER NOT NULL,
BOARD_NAME VARCHAR(255),
DEFAULT_ACCESS_LEVEL INTEGER,
LAST_POSTING_NUMBER INTEGER,
PARENT_BOARD_ID INTEGER
);

create table MESSAGE (
CONTENT VARCHAR(1024),
DATE_POSTED TIMESTAMP,
MESSAGE_ID INTEGER NOT NULL,
PARENT_MESSAGE_ID INTEGER,
PERSON_ID INTEGER NOT NULL,
SUBJECT VARCHAR(255)
);

create table PERSON (
CN VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255),
PERSON_ID INTEGER NOT NULL,
SEE_ALSO VARCHAR(255),
SN VARCHAR(255) NOT NULL,
TELEPHONE_NUMBER VARCHAR(255),
USER_PASSWORD varchar(32)
);

create table POSTING (
BOARD_ID INTEGER NOT NULL,
MESSAGE_ID INTEGER NOT NULL,
POSTING_NUMBER INTEGER,
POSTING_PRIORITY INTEGER
);

create table PROFILE (
ALIAS VARCHAR(255),
IS_ADMINSTRATOR INTEGER,
PERSON_ID INTEGER NOT NULL,
PROFILE_ID INTEGER NOT NULL UNIQUE,
REFRESH_PING_RATE INTEGER,
USER_DEFAULTS varchar(1024)
);

create table STATUS_RANGE (
END_POSTING_NUMBER INTEGER,
START_POSTING_NUMBER INTEGER,
STATUS_ID INTEGER NOT NULL UNIQUE,
SUBSCRIPTION_ID INTEGER NOT NULL
);

create table SUBSCRIPTION (
ACCESS_LEVEL INTEGER,
BOARD_ID INTEGER NOT NULL,
IS_FAVORITE INTEGER,
PERSON_ID INTEGER NOT NULL,
SHOULD_SEND_DIGEST INTEGER,
SUBSCRIPTION_ID INTEGER NOT NULL
);

