
protocol 'jdbc:derby:';
connect 'movies;create=true';

--  PK CUSTOMER_ID
--  AUTHORIZATION_DATE, EXPIRATION_DATE, NOT NULL DEFAULT = '0000-00-00 00:00:00'
CREATE TABLE creditcard (
  AUTHORIZATION_DATE TIMESTAMP,
  AUTHORIZATION_NUM CHAR(10) NOT NULL DEFAULT '',
  CARD_NUMBER CHAR(25) NOT NULL DEFAULT '',
  CUSTOMER_ID INTEGER NOT NULL DEFAULT 0,
  EXPIRATION_DATE TIMESTAMP,
  CLIMIT DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE customer (
  CITY CHAR(20) NOT NULL DEFAULT '',
  CUSTOMER_ID INTEGER NOT NULL DEFAULT 0,
  FIRST_NAME CHAR(20) NOT NULL DEFAULT '',
  LAST_NAME CHAR(30) NOT NULL DEFAULT '',
  MEMBER_SINCE TIMESTAMP DEFAULT NULL,
  PHONE CHAR(10) DEFAULT NULL,
  STATE CHAR(2) DEFAULT NULL,
  STREET_ADDRESS CHAR(50) DEFAULT NULL,
  ZIP CHAR(10) DEFAULT NULL
);

CREATE TABLE department (
  DEPT_ID BIGINT NOT NULL DEFAULT 0,
  NAME CHAR(50) NOT NULL DEFAULT '',
  SITE_ID INTEGER NOT NULL DEFAULT 0);

CREATE TABLE director (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  TALENT_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE employee (
  DEPARTMENT_ID BIGINT NOT NULL DEFAULT 0,
  FIRST_NAME CHAR(100) DEFAULT NULL,
  ID BIGINT NOT NULL DEFAULT 0,
  LAST_NAME CHAR(100) DEFAULT NULL,
  TITLE CHAR(100) DEFAULT NULL
);

CREATE TABLE fee (
  AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  DATE_PAID TIMESTAMP DEFAULT NULL,
  FEE_ID INTEGER NOT NULL DEFAULT 0,
  FEE_TYPE_ID INTEGER NOT NULL DEFAULT 0,
  RENTAL_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE feetype (
  ENABLED INTEGER NOT NULL DEFAULT 0,
  FEE_TYPE CHAR(15) NOT NULL DEFAULT '',
  FEE_TYPE_ID INTEGER NOT NULL DEFAULT 0,
  ORDER_BY INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE movie (
  CATEGORY CHAR(20) DEFAULT NULL,
  DATE_RELEASED TIMESTAMP DEFAULT NULL,
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  POSTER_NAME CHAR(100) DEFAULT NULL,
  RATED CHAR(10) DEFAULT NULL,
  REVENUE DECIMAL(10,2) DEFAULT NULL,
  STUDIO_ID INTEGER DEFAULT NULL,
  TITLE CHAR(100) NOT NULL DEFAULT '',
  TRAILER_NAME CHAR(100) DEFAULT NULL
);

CREATE TABLE movierole (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  ROLE_NAME CHAR(30) DEFAULT NULL,
  TALENT_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE plotsummary (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  SUMMARY VARCHAR(1000)
);

-- DATE_OUT TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
CREATE TABLE rental (
  CUSTOMER_ID INTEGER NOT NULL DEFAULT 0,
  DATE_OUT TIMESTAMP,
  DATE_RETURNED TIMESTAMP DEFAULT NULL,
  RENTAL_ID INTEGER NOT NULL DEFAULT 0,
  UNIT_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE rentalterms (
  CHECK_OUT_LENGTH INTEGER NOT NULL DEFAULT 0,
  COST DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  DEPOSIT_AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  NAME CHAR(20) NOT NULL DEFAULT '',
  RENTAL_TERMS_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE rentaluser (
  ACCESS_LEVEL INTEGER NOT NULL DEFAULT 0,
  CUSTOMER_ID INTEGER DEFAULT NULL,
  PASSWORD CHAR(20) NOT NULL DEFAULT '',
  USER_ID INTEGER NOT NULL DEFAULT 0,
  LOGIN CHAR(20) NOT NULL DEFAULT ''
);

CREATE TABLE review (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  REVIEW BLOB,
  REVIEW_ID INTEGER NOT NULL DEFAULT 0,
  REVIEWER VARCHAR(50) DEFAULT NULL
);

CREATE TABLE studio (
  BUDGET DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  NAME CHAR(40) NOT NULL DEFAULT '',
  STUDIO_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE talent (
  FIRST_NAME CHAR(20) NOT NULL DEFAULT '',
  LAST_NAME CHAR(30) NOT NULL DEFAULT '',
  TALENT_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE talentphoto (
  PHOTO BLOB,
  TALENT_ID INTEGER NOT NULL DEFAULT 0
);

-- DATE_ACQUIRED TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
CREATE TABLE unit (
  DATE_ACQUIRED TIMESTAMP,
  NOTES CHAR(100) DEFAULT NULL,
  UNIT_ID INTEGER NOT NULL DEFAULT 0,
  VIDEO_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE video (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  RENTAL_TERMS_ID INTEGER NOT NULL DEFAULT 0,
  VIDEO_ID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE voting (
  MOVIE_ID INTEGER NOT NULL DEFAULT 0,
  NUMBER_OF_VOTES INTEGER DEFAULT NULL,
  RUNNING_AVERAGE FLOAT DEFAULT NULL
);

