
protocol 'jdbc:derby:';
connect 'petstore;create=true';

create table ACCOUNT (
ADDR1 CHAR(80),
ADDR2 CHAR(40),
CITY CHAR(80),
COUNTRY CHAR(20),
EMAIL CHAR(80),
FIRSTNAME CHAR(80),
LASTNAME CHAR(80),
PASSWORD CHAR(20),
PHONE CHAR(80),
STATE CHAR(80),
STATUS CHAR(2),
ZIP CHAR(20),
USERID CHAR(80) NOT NULL
);

create table CATEGORY (
DESCN VARCHAR(255),
NAME CHAR(80),
CATID CHAR(10) NOT NULL
);

create table INVENTORY (
QTY INTEGER,
ITEMID CHAR(10) NOT NULL
);

create table ITEM (
ATTR1 CHAR(80),
ATTR2 CHAR(80),
ATTR3 CHAR(80),
ATTR4 CHAR(80),
ATTR5 CHAR(80),
PRODUCTID CHAR(10) NOT NULL,
STATUS CHAR(2),
SUPPLIER INTEGER,
ITEMID CHAR(10) NOT NULL,
UNITCOST DECIMAL(10,2),
LISTPRICE DECIMAL(10,2)
);

create table LINEITEM (
ITEMID CHAR(10),
QUANTITY INTEGER,
LINEITEMID INTEGER NOT NULL,
ORDERID INTEGER NOT NULL,
UNITPRICE DECIMAL(10,2)
);

create table ORDERS (
BILLADDR1 CHAR(80),
BILLADDR2 CHAR(80),
BILLCITY CHAR(80),
BILLCOUNTRY CHAR(20),
BILLSTATE CHAR(80),
BILLTOFIRSTNAME CHAR(80),
BILLTOLASTNAME CHAR(80),
BILLZIP CHAR(20),
CARDTYPE CHAR(80),
COURIER CHAR(80),
CREDITCARD CHAR(80),
EXPRDATE CHAR(7),
ORDERDATE TIMESTAMP,
SHIPADDR1 CHAR(80),
SHIPADDR2 CHAR(80),
SHIPCITY CHAR(80),
SHIPCOUNTRY CHAR(20),
SHIPSTATE CHAR(80),
SHIPTOFIRSTNAME CHAR(80),
SHIPTOLASTNAME CHAR(80),
SHIPZIP CHAR(20),
USERID CHAR(80),
ORDERID INTEGER NOT NULL,
TOTALPRICE DECIMAL(10,2)
);

create table ORDERSTATUS (
STATUS CHAR(2),
UPDATEDATE TIMESTAMP,
LINENUM INTEGER NOT NULL,
ORDERID INTEGER NOT NULL
);

create table PRODUCT (
CATEGORY CHAR(10) NOT NULL,
DESCN VARCHAR(255),
NAME CHAR(80),
PRODUCTID CHAR(10) NOT NULL
);

create table PROFILE (
BANNEROPT INTEGER,
FAVCATEGORY CHAR(30),
LANGPREF CHAR(80),
MYLISTOPT INTEGER,
USER_TYPE CHAR(80),
USERID CHAR(80) NOT NULL
);

create table SUPPLIER (
ADDR1 CHAR(80),
ADDR2 CHAR(80),
CITY CHAR(80),
NAME CHAR(80),
PHONE CHAR(80),
STATE CHAR(80),
STATUS CHAR(2),
ZIP CHAR(5),
SUPPID INTEGER NOT NULL
);

