
protocol 'jdbc:derby:';
connect 'vendor;create=true';

create table CUSTOMER (
ADDRESS CHAR(30),
CITY CHAR(30),
CUSTOMER_ID CHAR(30),
CUSTOMER_NAME CHAR(50),
OID INTEGER NOT NULL,
STATE CHAR(30),
ZIP4 CHAR(4),
ZIPCODE CHAR(5)
);

create table ORDERS (
MARKET_CHANNEL CHAR(50),
OID INTEGER NOT NULL,
OID_CUSTOMER INTEGER NOT NULL,
OID_ORDER_ITEMS INTEGER,
ORDER_NUMBER CHAR(30)
);

create table ORDER_ITEMS (
ITEM_NUMBER CHAR(30),
OID int NOT NULL,
OID_ORDER INTEGER NOT NULL,
QUANTITY INTEGER
);

